In [1]:
import os
import pandas as pd
import numpy as np
import json
from glob import glob
import matplotlib.pyplot as plt

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [28]:
df_vindr = pd.read_csv('/home/than/DeepLearning/cxr_concept/CheXzero/benchmark/results/simplified_auc_comparison_padchestt25_indianat25_vindrcxrt10/indiana_results.csv')
df_vindr.head()
df_vindr.columns.tolist()

df_vindr["CLEAR"] = df_vindr.apply(
    lambda row: f"{row['SFR-Mistral_auc']:.3f} ({row['SFR-Mistral_ci_lower']:.3f}, {row['SFR-Mistral_ci_upper']:.3f})", axis=1
)
df_vindr["CheXzero"] = df_vindr.apply(
    lambda row: f"{row['CheXzero_auc']:.3f} ({row['CheXzero_ci_lower']:.3f}, {row['CheXzero_ci_upper']:.3f})", axis=1
)
df_vindr["BiomedCLIP"] = df_vindr.apply(
    lambda row: f"{row['BiomedCLIP_auc']:.3f} ({row['BiomedCLIP_ci_lower']:.3f}, {row['BiomedCLIP_ci_upper']:.3f})", axis=1
)
df_vindr["OpenAICLIP"] = df_vindr.apply(
    lambda row: f"{row['OpenAI_CLIP_auc']:.3f} ({row['OpenAI_CLIP_ci_lower']:.3f}, {row['OpenAI_CLIP_ci_upper']:.3f})", axis=1
)

,dataset,label,n_positive,n_total,SFR-Mistral_auc,SFR-Mistral_ci_lower,SFR-Mistral_ci_upper,CheXzero_auc,CheXzero_ci_lower,CheXzero_ci_upper,...,Qwen3_8B_auc,Qwen3_8B_ci_lower,Qwen3_8B_ci_upper,SFR-Mistral_vs_Qwen3_8B_p_value,SFR-Mistral_vs_Qwen3_8B_diff,OpenAI_Small_auc,OpenAI_Small_ci_lower,OpenAI_Small_ci_upper,SFR-Mistral_vs_OpenAI_Small_p_value,SFR-Mistral_vs_OpenAI_Small_diff
0,indiana,airspace disease,224,7466,0.844856,0.821248,0.867517,0.729011,0.694862,0.763499,...,0.315914,0.285876,0.346266,0.000,0.528943,0.732719,0.704549,0.764086,0.002,0.112137
1,indiana,arthritis,65,7466,0.652362,0.584494,0.717812,0.351868,0.291864,0.412801,...,0.611638,0.539265,0.682493,0.539,0.040724,0.682679,0.615383,0.745551,0.627,-0.030317
2,indiana,atherosclerosis,233,7466,0.661020,0.629548,0.692036,0.665316,0.636031,0.695796,...,0.785496,0.761321,0.809183,0.002,-0.124476,0.602340,0.563156,0.639305,0.063,0.058680
3,indiana,calcified granuloma,510,7466,0.604594,0.579661,0.628907,0.478403,0.451752,0.501854,...,0.599801,0.575483,0.624119,0.868,0.004793,0.553937,0.527840,0.579893,0.037,0.050657
4,indiana,calcinosis,558,7466,0.586311,0.562265,0.608188,0.429066,0.405533,0.453315,...,0.600569,0.575443,0.624592,0.532,-0.014259,0.602132,0.577890,0.626471,0.492,-0.015822

['dataset',
 'label',
 'n_positive',
 'n_total',
 'SFR-Mistral_auc',
 'SFR-Mistral_ci_lower',
 'SFR-Mistral_ci_upper',
 'CheXzero_auc',
 'CheXzero_ci_lower',
 'CheXzero_ci_upper',
 'SFR-Mistral_vs_CheXzero_p_value',
 'SFR-Mistral_vs_CheXzero_diff',
 'BiomedCLIP_auc',
 'BiomedCLIP_ci_lower',
 'BiomedCLIP_ci_upper',
 'SFR-Mistral_vs_BiomedCLIP_p_value',
 'SFR-Mistral_vs_BiomedCLIP_diff',
 'OpenAI_CLIP_auc',
 'OpenAI_CLIP_ci_lower',
 'OpenAI_CLIP_ci_upper',
 'SFR-Mistral_vs_OpenAI_CLIP_p_value',
 'SFR-Mistral_vs_OpenAI_CLIP_diff',
 'BiomedBERT_auc',
 'BiomedBERT_ci_lower',
 'BiomedBERT_ci_upper',
 'SFR-Mistral_vs_BiomedBERT_p_value',
 'SFR-Mistral_vs_BiomedBERT_diff',
 'Qwen3_8B_auc',
 'Qwen3_8B_ci_lower',
 'Qwen3_8B_ci_upper',
 'SFR-Mistral_vs_Qwen3_8B_p_value',
 'SFR-Mistral_vs_Qwen3_8B_diff',
 'OpenAI_Small_auc',
 'OpenAI_Small_ci_lower',
 'OpenAI_Small_ci_upper',
 'SFR-Mistral_vs_OpenAI_Small_p_value',
 'SFR-Mistral_vs_OpenAI_Small_diff']

In [29]:
df_clip = df_vindr.filter([
 'label',
 'n_positive',
 'CLEAR',
 'CheXzero',
 'BiomedCLIP',
 'OpenAICLIP',
 ])
df_clip_p = df_vindr.filter([ 
 'label',
 'n_positive',
 'SFR-Mistral_vs_CheXzero_p_value',
 'SFR-Mistral_vs_CheXzero_diff',
 'SFR-Mistral_vs_BiomedCLIP_p_value',
 'SFR-Mistral_vs_BiomedCLIP_diff',
 'SFR-Mistral_vs_OpenAI_CLIP_p_value',
 'SFR-Mistral_vs_OpenAI_CLIP_diff'])
df_clip.sort_values(by='CLEAR', ascending=False)

,label,n_positive,CLEAR,CheXzero,BiomedCLIP,OpenAICLIP
20,pleural effusion,286,"0.935 (0.920, 0.948)","0.937 (0.921, 0.951)","0.775 (0.748, 0.802)","0.567 (0.530, 0.605)"
7,consolidation,53,"0.926 (0.902, 0.948)","0.874 (0.818, 0.926)","0.715 (0.645, 0.785)","0.485 (0.408, 0.568)"
25,pulmonary edema,87,"0.887 (0.852, 0.915)","0.920 (0.885, 0.948)","0.725 (0.676, 0.772)","0.457 (0.392, 0.518)"
21,pneumonia,77,"0.882 (0.845, 0.915)","0.823 (0.774, 0.877)","0.553 (0.491, 0.613)","0.532 (0.469, 0.594)"
27,pulmonary fibrosis,34,"0.881 (0.817, 0.933)","0.770 (0.688, 0.849)","0.655 (0.559, 0.738)","0.669 (0.568, 0.765)"
24,pulmonary congestion,135,"0.872 (0.844, 0.897)","0.892 (0.866, 0.917)","0.664 (0.619, 0.707)","0.525 (0.476, 0.577)"
0,airspace disease,224,"0.845 (0.821, 0.868)","0.729 (0.695, 0.763)","0.601 (0.567, 0.636)","0.503 (0.462, 0.544)"
5,cardiomegaly,655,"0.840 (0.827, 0.853)","0.902 (0.892, 0.913)","0.662 (0.642, 0.681)","0.485 (0.460, 0.509)"
12,infiltrate,116,"0.798 (0.759, 0.831)","0.733 (0.678, 0.786)","0.652 (0.599, 0.707)","0.504 (0.443, 0.562)"
15,mass,32,"0.794 (0.732, 0.851)","0.697 (0.613, 0.775)","0.657 (0.582, 0.728)","0.499 (0.406, 0.591)"
23,pulmonary atelectasis,616,"0.776 (0.758, 0.794)","0.756 (0.736, 0.774)","0.509 (0.483, 0.533)","0.512 (0.488, 0.536)"
26,pulmonary emphysema,74,"0.750 (0.680, 0.811)","0.833 (0.790, 0.871)","0.584 (0.523, 0.648)","0.559 (0.484, 0.628)"
22,pneumothorax,44,"0.735 (0.658, 0.806)","0.776 (0.706, 0.841)","0.524 (0.435, 0.607)","0.379 (0.300, 0.465)"
6,cicatrix,355,"0.729 (0.704, 0.754)","0.628 (0.600, 0.655)","0.533 (0.501, 0.564)","0.550 (0.520, 0.580)"
18,opacity,840,"0.717 (0.699, 0.734)","0.752 (0.735, 0.770)","0.517 (0.497, 0.537)","0.540 (0.521, 0.561)"
17,normal,2695,"0.681 (0.669, 0.693)","0.632 (0.620, 0.644)","0.530 (0.517, 0.543)","0.483 (0.469, 0.496)"
2,atherosclerosis,233,"0.661 (0.630, 0.692)","0.665 (0.636, 0.696)","0.546 (0.507, 0.582)","0.585 (0.548, 0.623)"
1,arthritis,65,"0.652 (0.584, 0.718)","0.352 (0.292, 0.413)","0.490 (0.422, 0.556)","0.500 (0.433, 0.569)"
9,emphysema,116,"0.647 (0.598, 0.697)","0.869 (0.846, 0.891)","0.482 (0.426, 0.538)","0.534 (0.476, 0.589)"
8,deformity,210,"0.641 (0.606, 0.678)","0.576 (0.535, 0.614)","0.546 (0.505, 0.585)","0.465 (0.426, 0.506)"
13,kyphosis,58,"0.624 (0.559, 0.689)","0.704 (0.647, 0.761)","0.504 (0.417, 0.585)","0.355 (0.271, 0.432)"
3,calcified granuloma,510,"0.605 (0.580, 0.629)","0.478 (0.452, 0.502)","0.495 (0.470, 0.522)","0.512 (0.486, 0.537)"
4,calcinosis,558,"0.586 (0.562, 0.608)","0.429 (0.406, 0.453)","0.506 (0.480, 0.532)","0.511 (0.485, 0.535)"
16,nodule,211,"0.586 (0.546, 0.625)","0.518 (0.480, 0.559)","0.510 (0.474, 0.546)","0.561 (0.522, 0.599)"
10,granuloma,103,"0.577 (0.523, 0.626)","0.411 (0.355, 0.466)","0.521 (0.466, 0.579)","0.547 (0.493, 0.602)"
29,spondylosis,126,"0.566 (0.514, 0.619)","0.439 (0.393, 0.485)","0.470 (0.420, 0.520)","0.577 (0.532, 0.625)"
19,osteophyte,137,"0.545 (0.502, 0.589)","0.602 (0.556, 0.647)","0.477 (0.422, 0.526)","0.542 (0.494, 0.591)"
11,granulomatous disease,213,"0.518 (0.482, 0.551)","0.555 (0.518, 0.595)","0.471 (0.437, 0.505)","0.498 (0.459, 0.535)"
28,scoliosis,177,"0.505 (0.458, 0.549)","0.600 (0.557, 0.642)","0.493 (0.450, 0.535)","0.526 (0.485, 0.568)"
14,lucency,51,"0.466 (0.391, 0.544)","0.332 (0.264, 0.408)","0.528 (0.457, 0.602)","0.487 (0.404, 0.578)"

In [27]:
len(df_clip)

55

In [30]:
def extract_auc(val):
    return float(val.split(" ")[0])

auroc_cols = ["CLEAR", "CheXzero", "BiomedCLIP", "OpenAICLIP"]
# Function to format the best AUROC with LaTeX bold
def bold_max_latex(row):
    aucs = [extract_auc(row[col]) for col in auroc_cols]
    max_idx = aucs.index(max(aucs))
    formatted = {}
    for i, col in enumerate(auroc_cols):
        val = row[col]
        if i == max_idx:
            formatted[col] = f"\\textbf{{{val}}}"
        else:
            formatted[col] = val
    return pd.Series(formatted)

# Apply the bolding
df_latex = df_clip.sort_values(by='CLEAR', ascending=False).copy()
df_latex[auroc_cols] = df_clip.apply(lambda row: pd.Series(bold_max_latex(row), index=auroc_cols), axis=1)
# df_latex = df_latex.sort_values(by='CLEAR', ascending=False)
# Export to LaTeX code string
latex_code = df_latex.to_latex(index=False, escape=False, column_format="llcccc")

# Print or save
print(latex_code)

\begin{tabular}{llcccc}
\toprule
label & n_positive & CLEAR & CheXzero & BiomedCLIP & OpenAICLIP \\
\midrule
pleural effusion & 286 & 0.935 (0.920, 0.948) & \textbf{0.937 (0.921, 0.951)} & 0.775 (0.748, 0.802) & 0.567 (0.530, 0.605) \\
consolidation & 53 & \textbf{0.926 (0.902, 0.948)} & 0.874 (0.818, 0.926) & 0.715 (0.645, 0.785) & 0.485 (0.408, 0.568) \\
pulmonary edema & 87 & 0.887 (0.852, 0.915) & \textbf{0.920 (0.885, 0.948)} & 0.725 (0.676, 0.772) & 0.457 (0.392, 0.518) \\
pneumonia & 77 & \textbf{0.882 (0.845, 0.915)} & 0.823 (0.774, 0.877) & 0.553 (0.491, 0.613) & 0.532 (0.469, 0.594) \\
pulmonary fibrosis & 34 & \textbf{0.881 (0.817, 0.933)} & 0.770 (0.688, 0.849) & 0.655 (0.559, 0.738) & 0.669 (0.568, 0.765) \\
pulmonary congestion & 135 & 0.872 (0.844, 0.897) & \textbf{0.892 (0.866, 0.917)} & 0.664 (0.619, 0.707) & 0.525 (0.476, 0.577) \\
airspace disease & 224 & \textbf{0.845 (0.821, 0.868)} & 0.729 (0.695, 0.763) & 0.601 (0.567, 0.636) & 0.503 (0.462, 0.544) \\
cardiomegaly & 655 & 0.840 (0.827, 0.853) & \textbf{0.902 (0.892, 0.913)} & 0.662 (0.642, 0.681) & 0.485 (0.460, 0.509) \\
infiltrate & 116 & \textbf{0.798 (0.759, 0.831)} & 0.733 (0.678, 0.786) & 0.652 (0.599, 0.707) & 0.504 (0.443, 0.562) \\
mass & 32 & \textbf{0.794 (0.732, 0.851)} & 0.697 (0.613, 0.775) & 0.657 (0.582, 0.728) & 0.499 (0.406, 0.591) \\
pulmonary atelectasis & 616 & \textbf{0.776 (0.758, 0.794)} & 0.756 (0.736, 0.774) & 0.509 (0.483, 0.533) & 0.512 (0.488, 0.536) \\
pulmonary emphysema & 74 & 0.750 (0.680, 0.811) & \textbf{0.833 (0.790, 0.871)} & 0.584 (0.523, 0.648) & 0.559 (0.484, 0.628) \\
pneumothorax & 44 & 0.735 (0.658, 0.806) & \textbf{0.776 (0.706, 0.841)} & 0.524 (0.435, 0.607) & 0.379 (0.300, 0.465) \\
cicatrix & 355 & \textbf{0.729 (0.704, 0.754)} & 0.628 (0.600, 0.655) & 0.533 (0.501, 0.564) & 0.550 (0.520, 0.580) \\
opacity & 840 & 0.717 (0.699, 0.734) & \textbf{0.752 (0.735, 0.770)} & 0.517 (0.497, 0.537) & 0.540 (0.521, 0.561) \\
normal & 2695 & \textbf{0.681 (0.669, 0.693)} & 0.632 (0.620, 0.644) & 0.530 (0.517, 0.543) & 0.483 (0.469, 0.496) \\
atherosclerosis & 233 & 0.661 (0.630, 0.692) & \textbf{0.665 (0.636, 0.696)} & 0.546 (0.507, 0.582) & 0.585 (0.548, 0.623) \\
arthritis & 65 & \textbf{0.652 (0.584, 0.718)} & 0.352 (0.292, 0.413) & 0.490 (0.422, 0.556) & 0.500 (0.433, 0.569) \\
emphysema & 116 & 0.647 (0.598, 0.697) & \textbf{0.869 (0.846, 0.891)} & 0.482 (0.426, 0.538) & 0.534 (0.476, 0.589) \\
deformity & 210 & \textbf{0.641 (0.606, 0.678)} & 0.576 (0.535, 0.614) & 0.546 (0.505, 0.585) & 0.465 (0.426, 0.506) \\
kyphosis & 58 & 0.624 (0.559, 0.689) & \textbf{0.704 (0.647, 0.761)} & 0.504 (0.417, 0.585) & 0.355 (0.271, 0.432) \\
calcified granuloma & 510 & \textbf{0.605 (0.580, 0.629)} & 0.478 (0.452, 0.502) & 0.495 (0.470, 0.522) & 0.512 (0.486, 0.537) \\
calcinosis & 558 & \textbf{0.586 (0.562, 0.608)} & 0.429 (0.406, 0.453) & 0.506 (0.480, 0.532) & 0.511 (0.485, 0.535) \\
nodule & 211 & \textbf{0.586 (0.546, 0.625)} & 0.518 (0.480, 0.559) & 0.510 (0.474, 0.546) & 0.561 (0.522, 0.599) \\
granuloma & 103 & \textbf{0.577 (0.523, 0.626)} & 0.411 (0.355, 0.466) & 0.521 (0.466, 0.579) & 0.547 (0.493, 0.602) \\
spondylosis & 126 & 0.566 (0.514, 0.619) & 0.439 (0.393, 0.485) & 0.470 (0.420, 0.520) & \textbf{0.577 (0.532, 0.625)} \\
osteophyte & 137 & 0.545 (0.502, 0.589) & \textbf{0.602 (0.556, 0.647)} & 0.477 (0.422, 0.526) & 0.542 (0.494, 0.591) \\
granulomatous disease & 213 & 0.518 (0.482, 0.551) & \textbf{0.555 (0.518, 0.595)} & 0.471 (0.437, 0.505) & 0.498 (0.459, 0.535) \\
scoliosis & 177 & 0.505 (0.458, 0.549) & \textbf{0.600 (0.557, 0.642)} & 0.493 (0.450, 0.535) & 0.526 (0.485, 0.568) \\
lucency & 51 & 0.466 (0.391, 0.544) & 0.332 (0.264, 0.408) & \textbf{0.528 (0.457, 0.602)} & 0.487 (0.404, 0.578) \\
\bottomrule
\end{tabular}

## linear probing exp

In [36]:
df_clear = pd.read_csv('/home/than/DeepLearning/cxr_concept/CheXzero/concepts/results/linear_probing_auc_comparison/sfr_mistral_detailed_results.csv')
df_chexzero = pd.read_csv('/home/than/DeepLearning/cxr_concept/CheXzero/concepts/results/linear_probing_auc_comparison/chexzero_detailed_results.csv')
df_biomedclip = pd.read_csv('/home/than/DeepLearning/cxr_concept/CheXzero/concepts/results/linear_probing_auc_comparison/biomedclip_detailed_results.csv')
df_openaiclip = pd.read_csv('/home/than/DeepLearning/cxr_concept/CheXzero/concepts/results/linear_probing_auc_comparison/openai_clip_detailed_results.csv')
df_openaiclip.head()

,label,openai_clip_mean_auc,openai_clip_std_auc,openai_clip_ci_lower,openai_clip_ci_upper,openai_clip_n_runs
0,Atelectasis,0.725825,0.000627,0.724847,0.727256,20
1,Cardiomegaly,0.689109,0.000898,0.687631,0.690774,20
2,Consolidation,0.738751,0.000348,0.738118,0.739381,20
3,Edema,0.770756,0.000861,0.769922,0.772970,20
4,Enlarged Cardiomediastinum,0.705032,0.000662,0.703953,0.706153,20

In [37]:
def format_df(df, model_name, auc_col, lower_col, upper_col):
    return df[["label", auc_col, lower_col, upper_col]].copy().rename(columns={
        auc_col: f"{model_name}_auc",
        lower_col: f"{model_name}_ci_lower",
        upper_col: f"{model_name}_ci_upper"
    })

clear = format_df(df_clear, "CLEAR", "sfr_mistral_mean_auc", "sfr_mistral_ci_lower", "sfr_mistral_ci_upper")
chexzero = format_df(df_chexzero, "CheXzero", "chexzero_mean_auc", "chexzero_ci_lower", "chexzero_ci_upper")
biomedclip = format_df(df_biomedclip, "BiomedCLIP", "biomedclip_mean_auc", "biomedclip_ci_lower", "biomedclip_ci_upper")
openai = format_df(df_openaiclip, "OpenAICLIP", "openai_clip_mean_auc", "openai_clip_ci_lower", "openai_clip_ci_upper")

# Merge all on label
df = clear.merge(chexzero, on="label").merge(biomedclip, on="label").merge(openai, on="label")

# Define model column groups
model_names = ["CLEAR", "CheXzero", "BiomedCLIP", "OpenAICLIP"]

# Format AUROC + CI and bold the max per row
def row_formatter(row):
    aucs = []
    for m in model_names:
        auc = row[f"{m}_auc"]
        low = row[f"{m}_ci_lower"]
        high = row[f"{m}_ci_upper"]
        aucs.append((m, auc, f"{auc:.3f} ({low:.3f}, {high:.3f})"))
    # Find the model with max AUROC
    max_model = max(aucs, key=lambda x: x[1])[0]
    # Create output row with bolding
    output = {}
    for m, auc, text in aucs:
        output[m] = f"\\textbf{{{text}}}" if m == max_model else text
    return pd.Series(output)

# Apply formatting to the merged df
formatted_df = df[["label"]].copy()
formatted_df[model_names] = df.apply(row_formatter, axis=1)

In [39]:
latex_code = formatted_df.to_latex(index=False, escape=False, column_format="lcccc")

# Print or save
print(latex_code)

\begin{tabular}{lcccc}
\toprule
label & CLEAR & CheXzero & BiomedCLIP & OpenAICLIP \\
\midrule
Atelectasis & \textbf{0.876 (0.876, 0.876)} & 0.844 (0.844, 0.845) & 0.735 (0.733, 0.737) & 0.726 (0.725, 0.727) \\
Cardiomegaly & 0.867 (0.867, 0.868) & \textbf{0.881 (0.881, 0.882)} & 0.724 (0.724, 0.725) & 0.689 (0.688, 0.691) \\
Consolidation & \textbf{0.905 (0.905, 0.905)} & 0.897 (0.896, 0.897) & 0.797 (0.795, 0.799) & 0.739 (0.738, 0.739) \\
Edema & 0.884 (0.884, 0.884) & \textbf{0.906 (0.905, 0.906)} & 0.804 (0.803, 0.804) & 0.771 (0.770, 0.773) \\
Enlarged Cardiomediastinum & 0.727 (0.727, 0.728) & \textbf{0.727 (0.726, 0.729)} & 0.694 (0.691, 0.699) & 0.705 (0.704, 0.706) \\
Fracture & \textbf{0.720 (0.719, 0.720)} & 0.673 (0.661, 0.682) & 0.411 (0.400, 0.421) & 0.289 (0.283, 0.298) \\
Lung Lesion & \textbf{0.886 (0.885, 0.886)} & 0.847 (0.844, 0.850) & 0.647 (0.640, 0.651) & 0.717 (0.711, 0.724) \\
Lung Opacity & \textbf{0.933 (0.933, 0.933)} & 0.895 (0.895, 0.896) & 0.777 (0.777, 0.778) & 0.794 (0.792, 0.796) \\
Pleural Effusion & \textbf{0.945 (0.945, 0.945)} & 0.935 (0.935, 0.936) & 0.809 (0.807, 0.811) & 0.762 (0.761, 0.765) \\
Pleural Other & 0.908 (0.908, 0.908) & \textbf{0.947 (0.945, 0.949)} & 0.915 (0.913, 0.917) & 0.652 (0.633, 0.683) \\
Pneumonia & \textbf{0.839 (0.838, 0.841)} & 0.752 (0.750, 0.756) & 0.606 (0.603, 0.614) & 0.705 (0.700, 0.709) \\
Pneumothorax & \textbf{0.894 (0.894, 0.894)} & 0.679 (0.678, 0.681) & 0.624 (0.621, 0.627) & 0.487 (0.485, 0.489) \\
Support Devices & \textbf{0.928 (0.928, 0.928)} & 0.852 (0.851, 0.852) & 0.796 (0.796, 0.796) & 0.753 (0.751, 0.756) \\
\bottomrule
\end{tabular}